# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取你的代码
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. 关键步骤：设置 Dart 环境
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      # 3. 安装依赖
      - name: Install dependencies
        run: dart pub get

      # 4. 运行你需要的后续命令（如分析或测试）
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test
